version: '3'
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: wheelbarrow
      POSTGRES_DB: musicmap

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8081"
    expose:
      - "8081"
    networks:
      - frontend
      - backend
    env_file:
      - api/.env
    environment:
      DB_HOST: db
      DB_PORT: "5432"

  vis:
    build:
      target: prod
      context: ./vis
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - frontend
    env_file:
      - vis/.env
    environment:
      # uses the connection details that a user would?
      BACKEND: http://api:8081
networks:
  frontend:
  backend:
