version: '3'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5332:5432"
    expose:
      - "5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: wheelbarrow
      POSTGRES_DB: musicmap

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - frontend
      - backend
    env_file:
      - api/.env
    environment:
      DB_HOST: db
      DB_PORT: "5432"

  vis:
    build:
      context: ./vis
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - frontend
    env_file:
      - vis/.env
    environment:
      # uses the connection details that a user would?
      VITE_BACKEND_HOST: http://localhost
      VITE_BACKEND_PORT: "5000"
networks:
  frontend:
  backend:
