version: '3'
services:
  db:
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    environment:
        POSTGRES_USER: exampleuser
        POSTGRES_PASSWORD: wheelbarrow
        POSTGRES_DB: musicmap
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - api/.envrc
    environment:
      - DB_HOST=db
      - DB_PORT=5432