version: '3'
services:
  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: wheelbarrow
      POSTGRES_DB: musicmap
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    env_file:
      - api/.env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  vis:
    build:
      context: ./vis
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - frontend
    env_file:
      - vis/.env
    environment:
      # uses the connection details that a user would?
      - VITE_BACKEND_HOST=http://localhost
      - VITE_BACKEND_PORT=5000
networks:
  frontend:
  backend:
