version: '3'
services:
  db:
    image: janusgraph/janusgraph
    restart: always
    ports:
      - "8182:8182"
    expose:
      - "8182"
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - frontend
      - backend
    env_file:
      - api/.env
    environment:
      DB_HOST: db
      DB_PORT: "8182"

  vis:
    build:
      target: prod
      context: ./vis
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - frontend
    env_file:
      - vis/.env
    environment:
      # uses the connection details that a user would?
      VITE_BACKEND_HOST: http://localhost
      VITE_BACKEND_PORT: "5000"
networks:
  frontend:
  backend:
