// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AlbumsColumns holds the columns for the "albums" table.
	AlbumsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AlbumsTable holds the schema information for the "albums" table.
	AlbumsTable = &schema.Table{
		Name:       "albums",
		Columns:    AlbumsColumns,
		PrimaryKey: []*schema.Column{AlbumsColumns[0]},
	}
	// ArtistsColumns holds the columns for the "artists" table.
	ArtistsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// ArtistsTable holds the schema information for the "artists" table.
	ArtistsTable = &schema.Table{
		Name:       "artists",
		Columns:    ArtistsColumns,
		PrimaryKey: []*schema.Column{ArtistsColumns[0]},
	}
	// ArtistWroteColumns holds the columns for the "artist_wrote" table.
	ArtistWroteColumns = []*schema.Column{
		{Name: "artist_id", Type: field.TypeInt},
		{Name: "album_id", Type: field.TypeInt},
	}
	// ArtistWroteTable holds the schema information for the "artist_wrote" table.
	ArtistWroteTable = &schema.Table{
		Name:       "artist_wrote",
		Columns:    ArtistWroteColumns,
		PrimaryKey: []*schema.Column{ArtistWroteColumns[0], ArtistWroteColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "artist_wrote_artist_id",
				Columns:    []*schema.Column{ArtistWroteColumns[0]},
				RefColumns: []*schema.Column{ArtistsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "artist_wrote_album_id",
				Columns:    []*schema.Column{ArtistWroteColumns[1]},
				RefColumns: []*schema.Column{AlbumsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AlbumsTable,
		ArtistsTable,
		ArtistWroteTable,
	}
)

func init() {
	ArtistWroteTable.ForeignKeys[0].RefTable = ArtistsTable
	ArtistWroteTable.ForeignKeys[1].RefTable = AlbumsTable
}
