// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"nubuscu/pretense/ent/album"
	"nubuscu/pretense/ent/artist"
	"nubuscu/pretense/ent/predicate"
	"nubuscu/pretense/ent/tag"
	"nubuscu/pretense/ent/topic"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlbumQuery is the builder for querying Album entities.
type AlbumQuery struct {
	config
	limit               *int
	offset              *int
	unique              *bool
	order               []OrderFunc
	fields              []string
	predicates          []predicate.Album
	withBy              *ArtistQuery
	withIncludedIn      *TopicQuery
	withTaggedWith      *TagQuery
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*Album) error
	withNamedBy         map[string]*ArtistQuery
	withNamedIncludedIn map[string]*TopicQuery
	withNamedTaggedWith map[string]*TagQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlbumQuery builder.
func (aq *AlbumQuery) Where(ps ...predicate.Album) *AlbumQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit adds a limit step to the query.
func (aq *AlbumQuery) Limit(limit int) *AlbumQuery {
	aq.limit = &limit
	return aq
}

// Offset adds an offset step to the query.
func (aq *AlbumQuery) Offset(offset int) *AlbumQuery {
	aq.offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AlbumQuery) Unique(unique bool) *AlbumQuery {
	aq.unique = &unique
	return aq
}

// Order adds an order step to the query.
func (aq *AlbumQuery) Order(o ...OrderFunc) *AlbumQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryBy chains the current query on the "by" edge.
func (aq *AlbumQuery) QueryBy() *ArtistQuery {
	query := &ArtistQuery{config: aq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(album.Table, album.FieldID, selector),
			sqlgraph.To(artist.Table, artist.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, album.ByTable, album.ByPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIncludedIn chains the current query on the "included_in" edge.
func (aq *AlbumQuery) QueryIncludedIn() *TopicQuery {
	query := &TopicQuery{config: aq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(album.Table, album.FieldID, selector),
			sqlgraph.To(topic.Table, topic.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, album.IncludedInTable, album.IncludedInPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTaggedWith chains the current query on the "tagged_with" edge.
func (aq *AlbumQuery) QueryTaggedWith() *TagQuery {
	query := &TagQuery{config: aq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(album.Table, album.FieldID, selector),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, album.TaggedWithTable, album.TaggedWithPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Album entity from the query.
// Returns a *NotFoundError when no Album was found.
func (aq *AlbumQuery) First(ctx context.Context) (*Album, error) {
	nodes, err := aq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{album.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AlbumQuery) FirstX(ctx context.Context) *Album {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Album ID from the query.
// Returns a *NotFoundError when no Album ID was found.
func (aq *AlbumQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{album.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AlbumQuery) FirstIDX(ctx context.Context) int {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Album entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Album entity is found.
// Returns a *NotFoundError when no Album entities are found.
func (aq *AlbumQuery) Only(ctx context.Context) (*Album, error) {
	nodes, err := aq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{album.Label}
	default:
		return nil, &NotSingularError{album.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AlbumQuery) OnlyX(ctx context.Context) *Album {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Album ID in the query.
// Returns a *NotSingularError when more than one Album ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AlbumQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{album.Label}
	default:
		err = &NotSingularError{album.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AlbumQuery) OnlyIDX(ctx context.Context) int {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Albums.
func (aq *AlbumQuery) All(ctx context.Context) ([]*Album, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aq *AlbumQuery) AllX(ctx context.Context) []*Album {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Album IDs.
func (aq *AlbumQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := aq.Select(album.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AlbumQuery) IDsX(ctx context.Context) []int {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AlbumQuery) Count(ctx context.Context) (int, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AlbumQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AlbumQuery) Exist(ctx context.Context) (bool, error) {
	if err := aq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AlbumQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlbumQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AlbumQuery) Clone() *AlbumQuery {
	if aq == nil {
		return nil
	}
	return &AlbumQuery{
		config:         aq.config,
		limit:          aq.limit,
		offset:         aq.offset,
		order:          append([]OrderFunc{}, aq.order...),
		predicates:     append([]predicate.Album{}, aq.predicates...),
		withBy:         aq.withBy.Clone(),
		withIncludedIn: aq.withIncludedIn.Clone(),
		withTaggedWith: aq.withTaggedWith.Clone(),
		// clone intermediate query.
		sql:    aq.sql.Clone(),
		path:   aq.path,
		unique: aq.unique,
	}
}

// WithBy tells the query-builder to eager-load the nodes that are connected to
// the "by" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithBy(opts ...func(*ArtistQuery)) *AlbumQuery {
	query := &ArtistQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	aq.withBy = query
	return aq
}

// WithIncludedIn tells the query-builder to eager-load the nodes that are connected to
// the "included_in" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithIncludedIn(opts ...func(*TopicQuery)) *AlbumQuery {
	query := &TopicQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	aq.withIncludedIn = query
	return aq
}

// WithTaggedWith tells the query-builder to eager-load the nodes that are connected to
// the "tagged_with" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithTaggedWith(opts ...func(*TagQuery)) *AlbumQuery {
	query := &TagQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	aq.withTaggedWith = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Album.Query().
//		GroupBy(album.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AlbumQuery) GroupBy(field string, fields ...string) *AlbumGroupBy {
	grbuild := &AlbumGroupBy{config: aq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aq.sqlQuery(ctx), nil
	}
	grbuild.label = album.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Album.Query().
//		Select(album.FieldCreatedAt).
//		Scan(ctx, &v)
func (aq *AlbumQuery) Select(fields ...string) *AlbumSelect {
	aq.fields = append(aq.fields, fields...)
	selbuild := &AlbumSelect{AlbumQuery: aq}
	selbuild.label = album.Label
	selbuild.flds, selbuild.scan = &aq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a AlbumSelect configured with the given aggregations.
func (aq *AlbumQuery) Aggregate(fns ...AggregateFunc) *AlbumSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AlbumQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aq.fields {
		if !album.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AlbumQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Album, error) {
	var (
		nodes       = []*Album{}
		_spec       = aq.querySpec()
		loadedTypes = [3]bool{
			aq.withBy != nil,
			aq.withIncludedIn != nil,
			aq.withTaggedWith != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Album).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Album{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(aq.modifiers) > 0 {
		_spec.Modifiers = aq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withBy; query != nil {
		if err := aq.loadBy(ctx, query, nodes,
			func(n *Album) { n.Edges.By = []*Artist{} },
			func(n *Album, e *Artist) { n.Edges.By = append(n.Edges.By, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withIncludedIn; query != nil {
		if err := aq.loadIncludedIn(ctx, query, nodes,
			func(n *Album) { n.Edges.IncludedIn = []*Topic{} },
			func(n *Album, e *Topic) { n.Edges.IncludedIn = append(n.Edges.IncludedIn, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withTaggedWith; query != nil {
		if err := aq.loadTaggedWith(ctx, query, nodes,
			func(n *Album) { n.Edges.TaggedWith = []*Tag{} },
			func(n *Album, e *Tag) { n.Edges.TaggedWith = append(n.Edges.TaggedWith, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range aq.withNamedBy {
		if err := aq.loadBy(ctx, query, nodes,
			func(n *Album) { n.appendNamedBy(name) },
			func(n *Album, e *Artist) { n.appendNamedBy(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range aq.withNamedIncludedIn {
		if err := aq.loadIncludedIn(ctx, query, nodes,
			func(n *Album) { n.appendNamedIncludedIn(name) },
			func(n *Album, e *Topic) { n.appendNamedIncludedIn(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range aq.withNamedTaggedWith {
		if err := aq.loadTaggedWith(ctx, query, nodes,
			func(n *Album) { n.appendNamedTaggedWith(name) },
			func(n *Album, e *Tag) { n.appendNamedTaggedWith(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range aq.loadTotal {
		if err := aq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AlbumQuery) loadBy(ctx context.Context, query *ArtistQuery, nodes []*Album, init func(*Album), assign func(*Album, *Artist)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Album)
	nids := make(map[int]map[*Album]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(album.ByTable)
		s.Join(joinT).On(s.C(artist.FieldID), joinT.C(album.ByPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(album.ByPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(album.ByPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*Album]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "by" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *AlbumQuery) loadIncludedIn(ctx context.Context, query *TopicQuery, nodes []*Album, init func(*Album), assign func(*Album, *Topic)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Album)
	nids := make(map[int]map[*Album]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(album.IncludedInTable)
		s.Join(joinT).On(s.C(topic.FieldID), joinT.C(album.IncludedInPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(album.IncludedInPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(album.IncludedInPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*Album]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "included_in" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (aq *AlbumQuery) loadTaggedWith(ctx context.Context, query *TagQuery, nodes []*Album, init func(*Album), assign func(*Album, *Tag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Album)
	nids := make(map[int]map[*Album]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(album.TaggedWithTable)
		s.Join(joinT).On(s.C(tag.FieldID), joinT.C(album.TaggedWithPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(album.TaggedWithPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(album.TaggedWithPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(sql.NullInt64)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := int(values[0].(*sql.NullInt64).Int64)
			inValue := int(values[1].(*sql.NullInt64).Int64)
			if nids[inValue] == nil {
				nids[inValue] = map[*Album]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tagged_with" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (aq *AlbumQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	if len(aq.modifiers) > 0 {
		_spec.Modifiers = aq.modifiers
	}
	_spec.Node.Columns = aq.fields
	if len(aq.fields) > 0 {
		_spec.Unique = aq.unique != nil && *aq.unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AlbumQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (aq *AlbumQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   album.Table,
			Columns: album.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: album.FieldID,
			},
		},
		From:   aq.sql,
		Unique: true,
	}
	if unique := aq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, album.FieldID)
		for i := range fields {
			if fields[i] != album.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AlbumQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(album.Table)
	columns := aq.fields
	if len(columns) == 0 {
		columns = album.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.unique != nil && *aq.unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedBy tells the query-builder to eager-load the nodes that are connected to the "by"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithNamedBy(name string, opts ...func(*ArtistQuery)) *AlbumQuery {
	query := &ArtistQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	if aq.withNamedBy == nil {
		aq.withNamedBy = make(map[string]*ArtistQuery)
	}
	aq.withNamedBy[name] = query
	return aq
}

// WithNamedIncludedIn tells the query-builder to eager-load the nodes that are connected to the "included_in"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithNamedIncludedIn(name string, opts ...func(*TopicQuery)) *AlbumQuery {
	query := &TopicQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	if aq.withNamedIncludedIn == nil {
		aq.withNamedIncludedIn = make(map[string]*TopicQuery)
	}
	aq.withNamedIncludedIn[name] = query
	return aq
}

// WithNamedTaggedWith tells the query-builder to eager-load the nodes that are connected to the "tagged_with"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (aq *AlbumQuery) WithNamedTaggedWith(name string, opts ...func(*TagQuery)) *AlbumQuery {
	query := &TagQuery{config: aq.config}
	for _, opt := range opts {
		opt(query)
	}
	if aq.withNamedTaggedWith == nil {
		aq.withNamedTaggedWith = make(map[string]*TagQuery)
	}
	aq.withNamedTaggedWith[name] = query
	return aq
}

// AlbumGroupBy is the group-by builder for Album entities.
type AlbumGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AlbumGroupBy) Aggregate(fns ...AggregateFunc) *AlbumGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the group-by query and scans the result into the given value.
func (agb *AlbumGroupBy) Scan(ctx context.Context, v any) error {
	query, err := agb.path(ctx)
	if err != nil {
		return err
	}
	agb.sql = query
	return agb.sqlScan(ctx, v)
}

func (agb *AlbumGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range agb.fields {
		if !album.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := agb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (agb *AlbumGroupBy) sqlQuery() *sql.Selector {
	selector := agb.sql.Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(agb.fields)+len(agb.fns))
		for _, f := range agb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(agb.fields...)...)
}

// AlbumSelect is the builder for selecting fields of Album entities.
type AlbumSelect struct {
	*AlbumQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AlbumSelect) Aggregate(fns ...AggregateFunc) *AlbumSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AlbumSelect) Scan(ctx context.Context, v any) error {
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	as.sql = as.AlbumQuery.sqlQuery(ctx)
	return as.sqlScan(ctx, v)
}

func (as *AlbumSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(as.sql))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		as.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		as.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := as.sql.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
