// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"nubuscu/pretense/ent/artist"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Artist is the model entity for the Artist schema.
type Artist struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MetaLabels holds the value of the "meta_labels" field.
	MetaLabels []string `json:"meta_labels,omitempty"`
	// SpotifyURL holds the value of the "spotify_url" field.
	SpotifyURL string `json:"spotify_url,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArtistQuery when eager-loading is set.
	Edges ArtistEdges `json:"edges"`
}

// ArtistEdges holds the relations/edges for other nodes in the graph.
type ArtistEdges struct {
	// Wrote holds the value of the wrote edge.
	Wrote []*Album `json:"wrote,omitempty"`
	// TaggedWith holds the value of the tagged_with edge.
	TaggedWith []*Tag `json:"tagged_with,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedWrote      map[string][]*Album
	namedTaggedWith map[string][]*Tag
}

// WroteOrErr returns the Wrote value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) WroteOrErr() ([]*Album, error) {
	if e.loadedTypes[0] {
		return e.Wrote, nil
	}
	return nil, &NotLoadedError{edge: "wrote"}
}

// TaggedWithOrErr returns the TaggedWith value or an error if the edge
// was not loaded in eager-loading.
func (e ArtistEdges) TaggedWithOrErr() ([]*Tag, error) {
	if e.loadedTypes[1] {
		return e.TaggedWith, nil
	}
	return nil, &NotLoadedError{edge: "tagged_with"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Artist) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case artist.FieldMetaLabels:
			values[i] = new([]byte)
		case artist.FieldID:
			values[i] = new(sql.NullInt64)
		case artist.FieldSpotifyURL, artist.FieldName:
			values[i] = new(sql.NullString)
		case artist.FieldCreatedAt, artist.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Artist", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Artist fields.
func (a *Artist) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case artist.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case artist.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				a.CreatedAt = value.Time
			}
		case artist.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				a.UpdatedAt = value.Time
			}
		case artist.FieldMetaLabels:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta_labels", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &a.MetaLabels); err != nil {
					return fmt.Errorf("unmarshal field meta_labels: %w", err)
				}
			}
		case artist.FieldSpotifyURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spotify_url", values[i])
			} else if value.Valid {
				a.SpotifyURL = value.String
			}
		case artist.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		}
	}
	return nil
}

// QueryWrote queries the "wrote" edge of the Artist entity.
func (a *Artist) QueryWrote() *AlbumQuery {
	return (&ArtistClient{config: a.config}).QueryWrote(a)
}

// QueryTaggedWith queries the "tagged_with" edge of the Artist entity.
func (a *Artist) QueryTaggedWith() *TagQuery {
	return (&ArtistClient{config: a.config}).QueryTaggedWith(a)
}

// Update returns a builder for updating this Artist.
// Note that you need to call Artist.Unwrap() before calling this method if this Artist
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Artist) Update() *ArtistUpdateOne {
	return (&ArtistClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the Artist entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Artist) Unwrap() *Artist {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Artist is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Artist) String() string {
	var builder strings.Builder
	builder.WriteString("Artist(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("created_at=")
	builder.WriteString(a.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(a.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("meta_labels=")
	builder.WriteString(fmt.Sprintf("%v", a.MetaLabels))
	builder.WriteString(", ")
	builder.WriteString("spotify_url=")
	builder.WriteString(a.SpotifyURL)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedWrote returns the Wrote named value or an error if the edge was not
// loaded in eager-loading with this name.
func (a *Artist) NamedWrote(name string) ([]*Album, error) {
	if a.Edges.namedWrote == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := a.Edges.namedWrote[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (a *Artist) appendNamedWrote(name string, edges ...*Album) {
	if a.Edges.namedWrote == nil {
		a.Edges.namedWrote = make(map[string][]*Album)
	}
	if len(edges) == 0 {
		a.Edges.namedWrote[name] = []*Album{}
	} else {
		a.Edges.namedWrote[name] = append(a.Edges.namedWrote[name], edges...)
	}
}

// NamedTaggedWith returns the TaggedWith named value or an error if the edge was not
// loaded in eager-loading with this name.
func (a *Artist) NamedTaggedWith(name string) ([]*Tag, error) {
	if a.Edges.namedTaggedWith == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := a.Edges.namedTaggedWith[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (a *Artist) appendNamedTaggedWith(name string, edges ...*Tag) {
	if a.Edges.namedTaggedWith == nil {
		a.Edges.namedTaggedWith = make(map[string][]*Tag)
	}
	if len(edges) == 0 {
		a.Edges.namedTaggedWith[name] = []*Tag{}
	} else {
		a.Edges.namedTaggedWith[name] = append(a.Edges.namedTaggedWith[name], edges...)
	}
}

// Artists is a parsable slice of Artist.
type Artists []*Artist

func (a Artists) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
