query AllTopics {
  topics {
    edges {
      node {
        id
        name
        metaLabels
        includes {
          id
          name
          spotifyURL
          by {
            id
            name
            spotifyURL
            metaLabels
          }
        }
        reviewedBy {
          id
          name
          body
          metaLabels
        }
      }
    }
  }
}
