query AllTopics {
    topics {
        edges {
            node {
                id
                name
                includes {
                    id
                    name
                    by {
                        id
                        name
                    }
                }
            }
        }
    }
}